token_auth.auth_token.*:
  type: config_entity
  label: 'Authentication Token config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    token:
      type: string
      label: 'Auth Token'
    enabled:
      type: boolean
      label: 'Enabled'
